### PR TITLE
Fix tests for selinux facts

### PR DESCRIPTION
**Pull request by ghost**
### Proposed changes
When trying to set some selinux values on the 0.2.0 release of this role, I found that the tests for selinux were broken. This PR should fix them.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works

   I haven't done this since it's doesn't seem trivial to incorporate selinux tests into a molecule + Docker test setup. I have tested on my own VM by setting these two values:

* nginx_config_selinux: true
* nginx_config_selinux_tcp_ports: "80,443,4180"

  If you'd prefer to not accept this PR without a molecule test, you can maybe just use it as a guide for what's broken and what needs fixing.

-   [X] I have checked that all Molecule tests pass after adding my changes

  All of the existing molecule tests that I was able to run (ie. the non-nginx plus scenarios) continue to pass.

-   [X] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)

   No documentation changes are needed.

### CODE REVIEW

**Comment by alessfg** [comment]
Ah I think the issue might have been with `ansible_facts['selinux.mode']`. Instead of going to the notation you used in the PR, could you simply try replacing `ansible_facts['selinux.mode']` with `ansible_facts['selinux']['mode']` and see if that fixes the issue on your end? If it does I'd rather you revert your other changes and simply make that simple change 😄 

One other thing -- the Changelog should be updated to include this change as a Bug Fix. It'll probably be included in release `0.2.1`.

**Comment by dudefellah** [comment]
Sure, I can make the syntax change. 

It might be safer to leave in the `'selinux' in ansible_facts` test since it's possible that `selinux` is just completely unset which would mean that looking for `ansible_facts['selinux'][mode']` will cause problems on non-selinux systems. Of course, you might argue that if someone has set `nginx_config_selinux` on a non-selinux system, they deserve what they get. If you still insist, I'll remove that test and update the syntax.

**Comment by alessfg** [comment]
Nah, I agree with your reasoning. Let's keep the `'selinux' in ansible_facts` check 😄

**Comment by dudefellah** [comment]
OK I think it should be good now.

**Comment by alessfg** [comment]
Made a couple minor styling changes to ensure that the style remained consistent. Thanks for the PR!

**Pull request merged**
