### PR TITLE
Rename html_file_name to index and add index to server_block

### PR DESCRIPTION
**Pull request by kutysam**
### Proposed changes
Server block should also be allowed to input html_file_name aka index.
(I feel it should have been named index all along. But i'll follow the convention written here)

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works
-   [x] I have checked that all Molecule tests pass after adding my changes
-   [X] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)

### CODE REVIEW

**Comment by alessfg** [comment]
I agree it should have been named `index` all along. The current name stems from the initial goal to abstract NGINX directives into a more understandable format. That being said, if you want to rename all `html_file_name` parameters to `index` as part of this PR, feel free to do so. Throw the change into the `Breaking Changes` Changelog though. While at it, can you add a simple test to Molecule?

**Comment by kutysam** [comment]
Sure. I'll refactor it sometime soon. I'm still new to molecule so it may take a little while.

**Comment by alessfg** [comment]
I went ahead and made the changes myself. Thanks for the initial PR contribution! 😄

**Comment by kutysam** [comment]
Sorry for the delay @alessfg . Thanks for patching it too.

**Pull request merged**
