### PR TITLE
Explicitly specify http_version as string

### PR DESCRIPTION
**Pull request by orlovmyk**
Explicitly specify http_version as string, because otherwise it's a number and ignored

### Proposed changes

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).

### Checklist

Before creating a PR, run through this checklist and mark each as complete:

- [x] I have read the [`CONTRIBUTING`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document.
- [x] I have added Molecule tests that prove my fix is effective or that my feature works.
- [x] I have checked that any relevant Molecule tests pass after adding my changes.
- [x] I have updated any relevant documentation ([`defaults/main/*.yml`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/), [`README.md`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/README.md) and [`CHANGELOG.md`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CHANGELOG.md)).

### CODE REVIEW

**Review by alessfg — CHANGES_REQUESTED** [review]
Thanks for the PR @orlovmyk! 

Nice catch! Can you change the parameter in the default and plus molecule tests and update the changelog?

Thanks! 😄

**Comment by orlovmyk** [comment]
@alessfg Made requested changes, thx for review

**Comment by orlovmyk** [comment]
@alessfg don't know why it's failing, errors doesn't have anything with my changes
Can you please check?
```
   RUNNING HANDLER [nginxinc.nginx_config : (Handler - NGINX Config) Print NGINX error if syntax check fails] ***
  fatal: [alpine-3.17]: FAILED! => {
      "config_check['stderr_lines']": [
          "nginx: [warn] duplicate MIME type \"text/html\" in /etc/nginx/conf.d/default.conf:246",
          "nginx: [emerg] \"listen\" directive \"so_keepalive\" parameter is incompatible with \"quic\" in /etc/nginx/conf.d/default.conf:300",
          "nginx: configuration file /etc/nginx/nginx.conf test failed"
      ],
      "failed_when_result": true
  }
  fatal: [debian-bullseye]: FAILED! => {
      "config_check['stderr_lines']": [
          "nginx: [warn] duplicate MIME type \"text/html\" in /etc/nginx/conf.d/default.conf:246",
          "nginx: [emerg] \"listen\" directive \"so_keepalive\" parameter is incompatible with \"quic\" in /etc/nginx/conf.d/default.conf:300",
          "nginx: configuration file /etc/nginx/nginx.conf test failed"
      ],
      "failed_when_result": true
  }
  fatal: [rhel-9]: FAILED! => {
      "config_check['stderr_lines']": [
          "nginx: [warn] duplicate MIME type \"text/html\" in /etc/nginx/conf.d/default.conf:246",
          "nginx: [emerg] \"listen\" directive \"so_keepalive\" parameter is incompatible with \"quic\" in /etc/nginx/conf.d/default.conf:300",
          "nginx: configuration file /etc/nginx/nginx.conf test failed"
      ],
      "failed_when_result": true
  }
  fatal: [ubuntu-jammy]: FAILED! => {
      "config_check['stderr_lines']": [
          "nginx: [warn] duplicate MIME type \"text/html\" in /etc/nginx/conf.d/default.conf:246",
          "nginx: [emerg] \"listen\" directive \"so_keepalive\" parameter is incompatible with \"quic\" in /etc/nginx/conf.d/default.conf:300",
          "nginx: configuration file /etc/nginx/nginx.conf test failed"
      ],
      "failed_when_result": true
  }
  ```

**Comment by alessfg** [comment]
The tests are failing due to a change in the latest nginx release. I'll hopefully have a fix for it sometime next week and then we can test this PR :)

**Comment by alessfg** [comment]
Quick update -- tests are passing but I want to test a different approach to validating float numbers locally before merging the PR :)

**Pull request closed without merging**
