### PR TITLE
Fixes #28: Use port 8080 by default for status page

### LINKED ISSUE #28: Status defaults shouldn't be to listen on port 80 without a server_name
**Describe the bug**
Having the stub_status module served via its own HTTP server on port 80 and without a server_name by default can give odd behaviour.
Having another HTTP host set as default_server isn't enough either to guarantee the separation.
The allow/deny statements should also be moved out of the */nginx_status* location to the server block.

**To reproduce**
1. Deploy NGINX role
2. Enable ```nginx_status_enable```
3. Configure another HTTP listener on port 80 (can be ```default_server```).
4. See random HTTP requests from bots getting lost on 

**Expected behavior**
The status page should by default be served in a context that does not conflict with any other port 80 listener deployed.
So either on a different port, or a location within an existing server block.

**Your environment:**
-   0.16.0
-   2.9
-   RHEL 7

### PR DESCRIPTION
**Pull request by tux-o-matic**
### Proposed changes
Fixes #28 by making 8080 the default port for the status page. Moved the status page ACL out of the location block to server to ensure it's applied to all requests. 
### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works (Molecule [test](https://github.com/nginxinc/ansible-role-nginx-config/blob/6b7e1e9156c9b1f350a6f68dc2c2a6933faa126b/molecule/default/converge.yml#L60) already used 8080)
-   [x] I have checked that all Molecule tests pass after adding my changes
-   [x] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)

### CODE REVIEW

**Comment by alessfg** [comment]
Can you update the Changelog @tux-o-matic?

**Comment by tux-o-matic** [comment]
@alessfg done

**Comment by alessfg** [comment]
Cool thanks! I'll merge the PR once I fix Travis 😄

**Comment by alessfg** [comment]
I'm pushing the TravisCI changes directly to your branch since it's the easiest way to fix that the conditionals I introduced are working properly 😄

**Pull request merged**
