### PR TITLE
Sub filter defaults fix

### PR DESCRIPTION
**Pull request by fr6nco**
### Proposed changes
sub_filter values in template are rendered using the ternary operator, which should be boolean values instead of "on"/"off" string values

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works
-   [x] I have checked that all Molecule tests pass after adding my changes
-   [x] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)

### CODE REVIEW

**Comment by alessfg** [comment]
By all accounts Ansible parses `on`/`off` as `true`/`false`, but that being said it does make sense to use `true`/`false` whenever possible for consistency.

**Comment by fr6nco** [comment]
I just tested. I set the option to "off":

```
 nginx_config_main_template:
   sub_filter:
     last_modified: "off"
     once: true
     types: "text/html"
```

based on template...line 101 of nginx.conf.j2

```
{% endif %}
{% if nginx_config_main_template.sub_filter.last_modified is defined %}
    sub_filter_last_modified  {{ nginx_config_main_template.sub_filter.last_modified | ternary("on", "off") }};
{% endif %}
```

the result should be off.

it is ...
```
    sub_filter_last_modified  on;
    sub_filter_once on;
```
tho


So seems like the On Off thingy doesn't work well with ternary operator

When set to false it is working as expected.

Could you please give some details, how to update the changelog?
Should I define a new tag? 0.4.0? or (0.3.1, perhaps?)

**Comment by alessfg** [comment]
Interesting, might be because the values are wrapped in quotes 🤔 
Re tag, use `0.3.1`, this is not a breaking change.

**Comment by fr6nco** [comment]
I believe using ` | bool ` filter in the template before the ternary operator could work

**Comment by fr6nco** [comment]
indeed the quotation marks broke the functionality. on off values without quotation marks work as well. | bool is not a good idea as "off" value is treated as True.

**Pull request merged**
